/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.desktop.carrinho;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projeto.fachada.Fachada;
import projeto.modelo.Carrinho;
import projeto.modelo.Usuario;

/**
 *
 * @author bboyrap
 */
public class FormCarrinho extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormCarrinho
     */
    private Usuario usuario;
    private List<Carrinho> lista;
    public FormCarrinho(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        listarCarrinhos();
    }
    
    public void listarCarrinhos(){
        Fachada fachada = new Fachada();
        this.lista = fachada.carrinhoListar(this.usuario.getId());
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"ID", "Quantidade de Itens", "Valor Total", "Status"});
            
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Usuário não possui carrinho.");
            }
            for (Carrinho c : lista) {
                modelo.addRow(new String[]{Integer.toString(c.getId()), Integer.toString(fachada.quantidadeItem(c.getId())), Integer.toString(fachada.valorTotalCarrinho(c.getId())), Boolean.toString(c.isStatus())});
            }
            jTableCarrinho.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "metodo listar carrinho");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonCriar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonDetalhes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarrinho = new javax.swing.JTable();

        setTitle("Carrinho");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonCriar.setText("Criar Novo Carrinho");
        jButtonCriar.setFocusable(false);
        jButtonCriar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCriar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCriar);
        jToolBar1.add(jSeparator1);

        jButtonDetalhes.setText("Detalhes do Carrinho");
        jButtonDetalhes.setFocusable(false);
        jButtonDetalhes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDetalhes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonDetalhes);

        jTableCarrinho.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinhos do cliente"));
        jTableCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCarrinho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarActionPerformed
        // TODO add your handling code here:
        //validacao se carrinho existe ( status 0), getCarrinho se existir
        //se nao setCarrinho..
    }//GEN-LAST:event_jButtonCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriar;
    private javax.swing.JButton jButtonDetalhes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTableCarrinho;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
