/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.desktop.os;

import Outras.GerarPdf;
import java.util.List;
import javax.swing.JOptionPane;
import projeto.fachada.Fachada;
import projeto.modelo.Carrinho;
import projeto.modelo.Endereco;
import projeto.modelo.Entrega;
import projeto.modelo.Funcionario;
import projeto.modelo.Os;

/**
 *
 * @author bboyrap
 */
public class FormAdicionarOs extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormOs
     */
    private Carrinho carrinho;
    private List<Endereco> listaEndereco;
    private List<Funcionario> listaFuncionario;
    Fachada fachada = new Fachada();
    
    public FormAdicionarOs(Carrinho c) {
        initComponents();
        this.carrinho = c;
        buscarEndereco();
        buscarFuncionario();
    }
    
    public void buscarEndereco(){
        try {
            this.listaEndereco = this.fachada.enderecoBuscar(this.carrinho.getUsuario().getId());
            if (this.listaEndereco.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Usuário não possui endereços associados, favor inserir um endereço primeiro.");
            }
            else{
                for (Endereco e : this.listaEndereco) {
                    jComboBoxLogradouro.addItem(e.getLogradouro());
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro:\n" + e.getMessage(), "Contate o suporte", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void buscarFuncionario(){
        try {
            this.listaFuncionario = this.fachada.funcionarioEntregador();
            if (listaEndereco.size() == 0) {
                JOptionPane.showMessageDialog(null, "Não existem entregadores cadastrados.");
            }else{
                for (Funcionario f : this.listaFuncionario) {
                    jComboBoxEntregador.addItem(f.getNome());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro:\n" + e.getMessage(), "Contate o suporte", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxLogradouro = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxEntregador = new javax.swing.JComboBox();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Ordem de Serviço"));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Carrinho do usuário:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(155, 27, 161, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("fulano");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(334, 27, 400, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Selecionar endereço:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(154, 60, 162, 28);

        jComboBoxLogradouro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxLogradouro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o logradouro..." }));
        jComboBoxLogradouro.setToolTipText("Selecione o logradouro para entrega");
        jPanel1.add(jComboBoxLogradouro);
        jComboBoxLogradouro.setBounds(334, 60, 400, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Selecionar entregador:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 142, 176, 22);

        jComboBoxEntregador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxEntregador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o nome..." }));
        jPanel1.add(jComboBoxEntregador);
        jComboBoxEntregador.setBounds(334, 136, 400, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 11, 764, 186);

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.setToolTipText("");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(330, 220, 100, 79);

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Grava a os no sistema e depois gera o pdf.
        try{
            Os os = new Os();
            Entrega entrega = new Entrega();
            //Os
            os.setCarrinho(this.carrinho);

            //Entrega
            entrega.setOs(os);
            //Endereco
            JOptionPane.showMessageDialog(null, "EOQ00");
            Endereco e = this.listaEndereco.get(jComboBoxEntregador.getSelectedIndex() - 1);//erro aqui
            JOptionPane.showMessageDialog(null, "EOQ11");
            Funcionario f = this.listaFuncionario.get(jComboBoxEntregador.getSelectedIndex() - 1);
            entrega.setEndereco(e);
            entrega.setFuncionario(f);
            entrega.setStatus(true);
            entrega.setOs(os);

            //Ordem de serviços
            os.setEntrega(entrega);
            JOptionPane.showMessageDialog(null, "EOQ9");

            this.fachada.osCadastrar(os);
            JOptionPane.showMessageDialog(null, "EOQ10");

            JOptionPane.showMessageDialog(null, "Ordem de serviço cadastrada no sistema.");

            //gerar pdf da ordem
            GerarPdf pdf = new GerarPdf(os);
            JOptionPane.showMessageDialog(null, "EOQ11");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro:\n" + e.getMessage(), "Contate o suporte", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxEntregador;
    private javax.swing.JComboBox jComboBoxLogradouro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
